### ISSUE TITLE
Частное сообщение об уязвимости

### ISSUE THREAD

**Issue by Sim4n6** [spbu-se/spbu_se_site#102]
Привет,

Не могли бы вы рассмотреть результаты этого отчета https://github.com/spbu-se/spbu_se_site/security/advisories/GHSA-5vfc-v7hg-pvwm

Обратите внимание, что доступ к URL-адресу имеют только сопровождающие и владельцы этого репозитория.

Примечание: используется автоматический перевод.

Спасибо
@Sim4n6

**Comment by Sim4n6** [comment]
@iakov ? @ASlugin ?

**Comment by iakov** [comment]
Because only a logged in authorized user can do this, and the server is not actually mission-critical component, I do not think this is a highly critical issue for us. Nevertheless, it should be fixed by limiting the filename.

**Comment by KirillSmirnov** [comment]
Fixed in the commit 5ad623eb0405260763046343c5785bc588d8a57d
