### ISSUE TITLE
Ошибка в поиске по руководителям работ

### ISSUE THREAD

**Issue by iakov** [spbu-se/spbu_se_site#112]
Поиск есть, но странный. Привожу пример руководителя, которого нет в поиске, хотя он назначен за темой.
![image](https://github.com/spbu-se/spbu_se_site/assets/706759/3c1b625a-35bf-4162-a322-0d53e86804ed)

**Comment by homka122** [comment]
Воиспрозвел баг локально у себя
- Создал тему, включив в уровень ВКР
- Добавил уникального руководителя ВКР
- Руководитель ВКР не появился в списке руководителей

![image](https://github.com/user-attachments/assets/497a7235-386a-49cb-8bd7-26e7fa2104ae)

Проблема в том, что поле `Руководитель` в форме содержит пользователей, являющимся руководителями **только** учебной практики, а не ВКР

**Comment by homka122** [comment]
Также, например, если руководитель ВКР является другой человек, то при фильтрации с этим человек тема не будет отображаться в результатах 
![image](https://github.com/user-attachments/assets/dac9ebbf-5100-4e49-90a3-d736ecd8796f)
![image](https://github.com/user-attachments/assets/d2ca0bce-aed8-4b45-b6a1-754a8caf76db)
