### ISSUE TITLE
Упростить URL страниц сайта

### ISSUE THREAD

**Issue by yurii-litvinov** [spbu-se/spbu_se_site#24]
Сейчас https://se.math.spbu.ru/diplomas/index.html работает, https://se.math.spbu.ru/diplomas нет. ...index.html отдаёт статическими сайтами 90-х, и, наверное, нетрудно поправить роуты так, чтобы https://se.math.spbu.ru/diplomas вело туда же. Не исключено, что для других страниц можно проделать то же самое.

**Comment by KirillSmirnov** [comment]
Fix in commit 65c23bd151d285fe4cf3e4e71f756bcf6e299ea6
