### ISSUE TITLE
Ошибра 404 в "Архиве курсовых и ВКР"

### ISSUE THREAD

**Issue by vkutuev** [spbu-se/spbu_se_site#31]
В архиве курсовых и ВКР на каждый чих выбрасывает на страницу https://se.math.spbu.ru/404.html.

Приведу 2 воспроизводимих сценария

1.
    1. Заходим на сайт https://se.math.spbu.ru/
    2. Студентам -> Архив курсовых и ВКР
    3. В фильтрах выбираем
        - Тип: **Бакалаврская ВКР**
        - Направление: **Программная инженерия (бакалавриат)**
    4. Получаем ошибку 404
2.
    1. Заходим на сайт https://se.math.spbu.ru/
    2. Студентам -> Архив курсовых и ВКР
    3. В фильтрах выбираем
        - Руководитель: **Григорьев С.В.**
    4. Скролим вниз, выбираем 5-ю страницу
    5. Получаем ошибку 404

И ещё во многих других случаях происходит переход на эту страницу.

**Comment by KirillSmirnov** [comment]
Fixed in commit 22683419ccf2a135e33b6416a3736c8a11c3b265
